module UnitSelection::LoadDefaultData
  def load_default_data
    @flag = 0
    @md = 501
    @max = 11000
    @datamax = 500
    @htg = 0.0
    @dstunit = 0

    @coef8 = 0.0; @coef11 = 0.0; @coef11a = 0.0; @coef11h = 0.0; @coef11p = 0.0; @coef12 = 0.0; @coef12a = 0.0; @coef12h = 0.0; @coef12p = 0.0; @coef13 = 0.0; @coef13a = 0.0; @coef13h = 0.0; @coef13p = 0.0; @coef14 = 0.0; @coef14a = 0.0; @coef14h = 0.0; @coef14p = 0.0; @coef15 = 0.0; @coef15a = 0.0; @coef15h = 0.0; @coef15p = 0.0; @coef16 = 0.0; @coef16a = 0.0; @coef16h = 0.0; @coef16p = 0.0; @coef17 = 0.0; @coef18 = 0.0; @coef19 = 0.0; @coef20 = 0.0; @coef21 = 0.0; @coef22 = 0.0;
    @a0 = 0.0; @a1 = 0.0; @a2 = 0.0; @a3 = 0.0; @a4 = 0.0; @a5 = 0.0; @a6 = 0.0; @coef1 = 0.0; @coef2 = 0.0; @coef3 = 0.0; @coef4 = 0.0; @coef5 = 0.0; @coef6 = 0.0; @coef7 = 0.0; @coef8 = 0.0;

    @tm = Array.new(@md, 0.0)
    @ntm = Array.new(@md, 0.0)
    @tmpt = Array.new(@md, 0.0)
    @tma = Array.new(@md, 0.0)
    @tmh = Array.new(@md, 0.0)

    @itg = 0
    @iu = 0
    @xb = 0
    @up = 0
    @ptg = 0
    @xbp = 0
    @up2 = 0
    @xbp2 = 0
    @p2tg = 0
    @rph = 0
    @tg = Array.new(@md.next, 0.0)
    @ntg = Array.new(@md.next, 0.0)
    @tgpt = Array.new(@md.next, 0.0)
    @tga = Array.new(@md, 0.0)
    @tgh = Array.new(@md, 0.0)
    @c = Array.new(@md.next, 0.0)
    @nc = Array.new(@md.next, 0.0)
    @ceq = Array.new(@md, 0.0)
    @nceq = Array.new(@md, 0.0)
    @xs = Array.new(@md, 0.0)
    @q = Array.new(@md, 0.0)
    @nq = Array.new(@md, 0.0)
    @qpt = Array.new(@md, 0.0)
    @qa = Array.new(@md, 0.0)
    @qh = Array.new(@md, 0.0)
    @nx = Array.new(@md.next, 0.0)
    @xpt = Array.new(@md.next, 0.0)
    @xx = Array.new(@md.next, 0.0)
    @cpg = Array.new(@md, 0.0)

    @itg = 0
    @iu = 0
    @xb = 0
    @up = 0
    @ptg = 0
    @xbp = 0
    @up2 = 0
    @xbp2 = 0
    @p2tg = 0
    @rph = 0
    @adiv = 0
    @hdiv = 0
    @pdiv = 0
    @p2div = 0
    @kmassf = 0
    @hsvp = 0
    @itgc = 0
    @kmassr = 0
    @xbrh = 0
    @xbdp = 0
    @xbprh = 0
    @xbpdp = 0
    @optrot = 0.0

    @prestepcenth = Array.new(@md, 0.0)
    @datatext = Array.new(@datamax, "")
    @datatextu = Array.new(@datamax, "")
    @datatextr = Array.new(@datamax, "")
    @datatexts = Array.new(@datamax, "")
    @datavalue = Array.new(@datamax, Array.new(@datamax, 0.0))
    @datavalue1 = Array.new(@datamax, Array.new(@datamax, 0.0))
    # @coefa = Array.new(1000, Array.new(1000, 0.0))
    @flagd = Array.new(20, 0)
    @b = ""
    @abc = ""
    @aaa = ""

    @aaaa = Array.new(1000, Array.new(50, ""))
    @aabb = Array.new(1000, Array.new(50, ""))
    @aaaapara = Array.new(100, Array.new(50, ""))
    @cc = Array.new(1000, Array.new(500, 0.0))
    @ccpara = Array.new(100, Array.new(50, 0.0))
    @opq = 0


    @label1 = "TP1"
    @textbox1 = "10"
    @textbox2 = "140"
    @label2 = "TR1"
    @textbox3 = "Inlet Condition.csv"
    @label3 = "File Name"
    @textbox5_enabled = false
    @textbox5 = "6"
    @textbox7 = "6"
    @label6 = "Rotor Diameter"
    @label7 = "XP1"
    @textbox8_backcolor = "Color::White"
    @textbox8_enabled = false
    @textbox8 = "16"
    @label8 = "Rotation Rate [rph]"
    @textbox9_enabled = false
    @textbox9 = "270"
    @textbox9_visible = false
    @label11 = "Depth"
    @textboxd = "2"
    @label13 = "VP"
    @textboxe_enabled = false
    @textboxe = "2"
    @label14 = "VR"
    @textbox11_enabled = false
    @textbox11 = "45"
    @textbox11_visible = false
    @textbox14 = "1"
    @label21 = "Number of Conditions"
    @label24 = "XR1"
    @combobox1_backcolor = "Color::White"
    @combobox1 = 320
    @combobox2_backcolor = "Color::White"
    @combobox2 = "1:3"
    @label16 = "Category"
    @label17 = "Rotor"
    @combobox3_backcolor = "Color::White"
    @combobox3 = "D-MAX 200cpsi"
    @checkbox1 = true
    @checkbox2 = true
    @combobox4_backcolor = "Color::White"
    @combobox4 = "200"
    @textboxc_backcolor = "Color::White"
    @textboxc_enabled = false
    @textboxc_visible = false
    @checkbox3 = false
    @checkbox3_visible = false
    @groupbox2_backcolor = "Color::LightGreen"
    @groupbox2 = "A. Process Air Inlet"
    @label150 = "SFM"
    @textbox89 = "2"
    @label128 = "3"
    @label67 = "%RH"
    @label48 = "CFM"
    @label48_visible = false
    @textbox41_enabled = false
    @textbox41 = "78"
    @label68 = " °CDP"
    @textbox23_enabled = false
    @textbox23 = "400"
    @textbox42_enabled = false
    @textbox42 = "6"
    @textbox29_enabled = false
    @textbox29 = "250"
    @textbox29_visible = false
    @label40 = "FP"
    @label49 = "gr/lb"
    @label49_visible = false
    @label35 = "m /h"
    @textbox30_enabled = false
    @textbox30_visible = false
    @label50 = "FDB"
    @label50_visible = false
    @textbox31_enabled = false
    @textbox31 = "50"
    @textbox31_visible = false
    @label37 = "m/s"
    @label38 = "g/kg"
    @label39 = " °C"
    @label101 = "(at 20 °C)"
    @groupbox3_backcolor = "Color::LightSalmon"
    @groupbox3 = "F. Regeneration Inlet"
    @checkbox20 = false
    @checkbox20_visible = false
    @label71 = "°CDP"
    @label71_visible = false
    @textbox90_enabled = false
    @textbox90 = "2"
    @label151 = "SFM"
    @label129 = "3"
    @label98 = "m/s"
    @label70 = "%RH"
    @textbox45_enabled = false
    @textbox45 = "1"
    @textbox46_enabled = false
    @textbox46 = "6"
    @textbox46_visible = false
    @label59 = "m /h"
    @textbox38_enabled = false
    @textbox38 = "150"
    @label60 = "FR"
    @label57 = "g/kg"
    @label58 = " °C"
    @label51 = "CFM"
    @label51_visible = false
    @textbox32_enabled = false
    @textbox32 = "100"
    @textbox32_visible = false
    @label52 = "gr/lb"
    @label52_visible = false
    @textbox33_enabled = false
    @textbox33_visible = false
    @label53 = "FDB"
    @label53_visible = false
    @textbox34_enabled = false
    @textbox34 = "284"
    @textbox34_visible = false
    @groupbox4_backcolor = "Color::LightYellow"
    @groupbox4 = "B. Process Outlet"
    @checkbox21 = true
    @checkbox21_visible = false
    @textbox84_enabled = false
    @textbox84_visible = false
    @label145 = "CFM"
    @label145_visible = false
    @label141 = "FR"
    @label94 = "3"
    @textbox62 = "5"
    @label95 = "%"
    @label81 = "MR"
    @label79 = "lb/h"
    @label79_visible = false
    @textbox51_enabled = false
    @textbox51_visible = false
    @label80 = "kg/h"
    @textbox52_enabled = false
    @label66 = "%RH"
    @textbox43_enabled = false
    @label69 = " °CDP"
    @textbox44_enabled = false
    @label62 = "g/kg"
    @label63 = " °C"
    @label55 = "gr/lb"
    @label55_visible = false
    @textbox36_enabled = false
    @textbox36_visible = false
    @label56 = "FDB"
    @label56_visible = false
    @textbox37_enabled = false
    @textbox37_visible = false
    @textbox12_enabled = false
    @label10 = "XP2"
    @textbox17_enabled = false
    @label15 = "TP2"
    @textbox64_enabled = false
    @label111 = "m /h"
    @groupbox5_backcolor = "Color::White"
    @groupbox5 = "Condition"
    @checkbox23 = false
    @label127 = "Unit"
    @combobox8_backcolor = "Color::White"
    @checkbox17 = false
    @checkbox17_visible = false
    @checkbox16 = false
    @checkbox16_visible = false
    @checkbox15 = false
    @checkbox15_visible = false
    @checkbox14 = false
    @checkbox14_visible = false
    @checkbox13 = false
    @checkbox13_visible = false
    @checkbox11 = false
    @checkbox11_visible = false
    @checkbox10 = false
    @checkbox10_visible = false
    @checkbox9_enabled = false
    @checkbox9_visible = false
    @checkbox8 = true
    @checkbox8_visible = false
    @checkbox7 = false
    @checkbox7_visible = false
    @label12 = "kg/m3"
    @label12_visible = false
    @label154 = "0"
    @label153 = "No"
    @groupbox6_backcolor = "Color::LightSalmon"
    @groupbox6 = "D. Purge Outlet"
    @label76 = " °C"
    @textbox35_enabled = false
    @textbox35_visible = false
    @textbox18_enabled = false
    @label77 = "FDB"
    @label77_visible = false
    @label19 = "TPu2"
    @label61 = "kW"
    @label54 = "BTU/h"
    @label54_visible = false
    @groupbox7_backcolor = "Color::LightGreen"
    @groupbox7 = "E. OA"
    @textbox83_enabled = false
    @textbox83_visible = false
    @label144 = "CFM"
    @label144_visible = false
    @label93 = "3"
    @label36 = "FOA"
    @checkbox19 = false
    @label72 = "gr/lb"
    @label72_visible = false
    @textbox47_enabled = false
    @textbox47_visible = false
    @label73 = "FDB"
    @label73_visible = false
    @textbox48_enabled = false
    @textbox48_visible = false
    @label74 = "g/kg"
    @label75 = " °C"
    @label5 = "XOA"
    @textbox10 = "30"
    @textbox19_enabled = false
    @textbox19 = "1"
    @label28 = "TOA"
    @textbox65_enabled = false
    @textbox65 = ""
    @label113 = "m /h"
    @groupbox8_backcolor = "Color::LightBlue"
    @groupbox8 = "G. Regeneration Outlet"
    @label131 = "%RH"
    @textbox75_enabled = false
    @label130 = " °CDP"
    @label43 = "gr/lb"
    @label43_visible = false
    @textbox74_enabled = false
    @textbox24_enabled = false
    @textbox24_visible = false
    @label44 = "FDB"
    @label44_visible = false
    @textbox25_enabled = false
    @textbox25_visible = false
    @label41 = "g/kg"
    @textbox20_enabled = false
    @label42 = " °C"
    @label26 = "XR2"
    @textbox21_enabled = false
    @label27 = "TR2"
    @textbox15_enabled = false
    @textbox15 = "45"
    @textbox15_visible = false
    @label23 = "VPu"
    @textbox16_enabled = false
    @textbox16 = "2"
    @label25 = "XPu1"
    @label4 = "TPu1"
    @textbox6_enabled = false
    @textbox6 = "1"
    @textbox4_enabled = false
    @textbox4 = 10
    @checkbox4 = true
    @checkbox5 = true
    @checkbox6 = true
    @label29 = " °C"
    @label30 = "g/kg"
    @label34 = "FPu"
    @label31 = "m/s"
    @textbox27_enabled = false
    @textbox27 = "50"
    @textbox27_visible = false
    @textbox22_enabled = false
    @textbox22 = "2"
    @label46 = "FDB"
    @label46_visible = false
    @textbox26_enabled = false
    @textbox26_visible = false
    @label33 = "m /h"
    @label45 = "gr/lb"
    @label45_visible = false
    @textbox28_enabled = false
    @textbox28_visible = false
    @label47 = "CFM"
    @label47_visible = false
    @textbox40_enabled = false
    @textbox40 = "-15"
    @textbox40_visible = false
    @label65 = " °CDP"
    @label65_visible = false
    @textbox39_enabled = false
    @textbox39 = "13"
    @label64 = "%RH"
    @groupbox1_backcolor = "Color::LightGreen"
    @groupbox1 = "C\'. Purge Air Inlet"
    @label132 = "3"
    @label133 = "CFM"
    @label133_visible = false
    @textbox78_enabled = false
    @textbox78_visible = false
    @label134 = "m /h"
    @textbox79_enabled = false
    @textbox79 = "2"
    @label135 = "FPu"
    @label117 = "3"
    @label102 = "(at 20 °C)"
    @textbox13 = "Case1"
    @label20 = "Project "
    @groupbox9_backcolor = "Color::Tomato"
    @groupbox9 = "Heater"
    @textbox49_enabled = false
    @textbox49_visible = false
    @textbox50_enabled = false
    # @textbox50 = "0"
    @label78 = "HP"
    @groupbox10_backcolor = "Color::White"
    @groupbox10 = "Pressure Drop"
    @label114 = "in. wc"
    @label114_visible = false
    @textbox72_enabled = false
    @textbox72_visible = false
    @label115 = "Pa"
    @label116 = "PPu"
    @textbox73_enabled = false
    @label82 = "in. wc"
    @label82_visible = false
    @textbox53_enabled = false
    @textbox53_visible = false
    @label83 = "in. wc"
    @label83_visible = false
    @textbox54_enabled = false
    @textbox54_visible = false
    @label84 = "Pa"
    @label85 = "Pa"
    @label86 = "PR"
    @textbox55_enabled = false
    @textbox56_enabled = false
    @label87 = "PP"
    @label88 = "Date "
    @radiobutton1 = true
    @radiobutton7_enabled = false
    @radiobutton3 = true
    @radiobutton4_enabled = false
    @radiobutton5 = true
    @radiobutton10 = true
    @radiobutton11 = false
    @groupbox11 = "Flow Amount Select"
    @groupbox11_visible = false
    @groupbox12 = "Humidity Select"
    @groupbox12_visible = false
    @checkbox12 = false
    @checkbox12_visible = false
    @groupbox13_backcolor = "Color::GreenYellow"
    @groupbox13 = "A\'. Process Air Inlet"
    @groupbox13_visible = false
    @label149 = "CFM"
    @label149_visible = false
    @textbox88 = "200"
    @textbox88_visible = false
    @label32 = "3"
    @label22 = "m /h"
    @textbox80 = "200"
    @label89 = "gr/lb"
    @label89_visible = false
    @textbox58_enabled = false
    @textbox58_visible = false
    @label90 = "FDB"
    @label90_visible = false
    @textbox59_enabled = false
    @textbox59_visible = false
    @label91 = "g/kg"
    @label92 = " °C"
    @textbox60 = "20"
    @textbox61 = "8"
    @groupbox14 = "Unit Select"
    @groupbox15 = "Heater Select"
    @checkbox18 = true
    @checkbox18_visible = false
    @label103_backcolor = "Color::Transparent"
    @label103 = "%"
    @label103_visible = false
    @textbox66_backcolor = "Color::LightGreen"
    @textbox66 = "0"
    @textbox66_visible = false
    @label104_backcolor = "Color::Transparent"
    @label104 = "%"
    @label104_visible = false
    @textbox67_backcolor = "Color::LightGreen"
    @textbox67 = "50"
    @textbox67_visible = false
    @label105_backcolor = "Color::Transparent"
    @label105 = "%"
    @label105_visible = false
    @label106_backcolor = "Color::Transparent"
    @label106 = "%"
    @label106_visible = false
    @label107 = "m"
    @label107_visible = false
    @label109 = "2"
    @label110 = "Total Area"
    @label110_visible = false
    @label112_backcolor = "Color::Transparent"
    @label112 = "1"
    @label112_visible = false
    @label118_backcolor = "Color::Transparent"
    @label118 = "%"
    @label118_visible = false
    @label119_backcolor = "Color::Transparent"
    @label119 = "%"
    @label119_visible = false
    @label120 = "A"
    @label121 = "C\'"
    @label122 = "B"
    @label123 = "D"
    @label124 = "E"
    @label125 = "F"
    @label126 = "G"
    @textbox68 = "75"
    @textbox68_visible = false
    @textbox69 = "25"
    @textbox69_visible = false
    @textbox70 = "0"
    @textbox70_visible = false
    @textbox71 = "0"
    @textbox71_visible = false
    @groupbox16_backcolor = "Color::LightGreen"
    @groupbox16 = "C. Purge Inlet"
    @label152 = "SFM"
    @textbox91_enabled = false
    @textbox91 = "2"
    @label136 = "C"
    @label137 = "D\'"
    @label97 = "A\'"
    @label138 = "P"
    @textbox77 = "0"
    @label100 = "(             mbar)"
    @label99 = "m"
    @groupbox17_backcolor = "Color::White"
    @groupbox17 = "Height above sea leve"
    @label139 = "1013"
    @groupbox18_backcolor = "Color::OliveDrab"
    @groupbox18 = "C\'\'. Regen Air Inlet"
    @groupbox18_visible = false
    @textbox87_enabled = false
    @textbox87_visible = false
    @label148 = "FDB"
    @label148_visible = false
    @textbox86_enabled = false
    @textbox86_visible = false
    @label147 = "gr/lb"
    @label147_visible = false
    @textbox85_enabled = false
    @textbox85_visible = false
    @label146 = "CFM"
    @label146_visible = false
    @label18 = "3"
    @label9 = "m /h"
    @textbox76 = "200"
    @label142 = "g/kg"
    @label143 = " °C"
    @textbox81 = "20"
    @textbox82 = "8"
    @label140 = "C\'\'"
    @groupbox19 = "Coef."
    @checkbox22 = false
    @label166 = "ε2"
    @label164 = "ε1"
    @label160 = "No"
    @label161 = "0"
    @label162 = "0"
    @label162_visible = false
    @label163 = "Coef11"
    @label163_visible = false
    @label159 = "kmassr"
    @label158 = "0"
    @label157 = "0"
    @label156 = "kmassf"
    @label108 = "Coef7a"
    @label108_visible = false
    @label155 = "0"
    @label155_visible = false
    @dsttoolstripmenuitem = "-DST"
    @dstreptoolstripmenuitem = "-Rep"
    @radiobutton8 = true
    @radiobutton9 = false
    @radiobutton6 = false

    @iiii = 0
  end
end